### ISSUE TITLE
Missing antsdr board folder or spec file

### ISSUE THREAD

**Issue by schelleg** [MicroPhase/antsdr-pynq#1]
From the README steps, is there a missing folder called "antsdr" at the toplevel?  I want to try rebuilding, but image building would need that folder.  Please let me know if I'm missing a step.  

```
mkdir sdbuild/prebuilt
unzip -d  sdbuild/prebuilt  pynq_rootfs_arm_v2.4.zip
cd sdbuild
make BOARDS=../../antsdr  PREBUILT=./prebuilt/bionic.arm.2.4.img  #### ../../antsdr does not exist?
```

**Comment by black-pigeon** [comment]
oppps, there was a mistake. We moved the board into the pynq folder, but forgot to update the submodule. We will update this later.

**Comment by schelleg** [comment]
thank you ... I am now able to rebuild the image.
