### ISSUE TITLE
AD9363 support

### ISSUE THREAD

**Issue by schelleg** [MicroPhase/antsdr-pynq#2]
I see the AD9363's E310s are available, but perhaps AD9361's are out of stock ...

Is it possible to port 9361 examples / sdcard image to the AD9363 rev or is this too much work?

![image](https://user-images.githubusercontent.com/12449034/133858865-26a9db3f-bbe1-482c-8f47-88f7b489b35c.png)
https://www.aliexpress.com/item/1005003181244737.html

**Comment by black-pigeon** [comment]
The ad9361 and ad9363 could use the same image. The version of AD9361 has been sold out and is now preparing for the next production.

**Comment by schelleg** [comment]
thank you for information.  Great to hear its selling out.
