### ISSUE TITLE
can't see ad9363 in e200 PYNQ

### ISSUE THREAD

**Issue by Mojosekiz** [MicroPhase/antsdr-pynq#5]
i'm downladed image from link. then copy it to sd card.
after boot i try to follow steps on how to setup pynq.
first i found libiio v0.24 already installed.
then i download libad9361 as mentioned 
then i try this command 

```
xilinx@pynq:~$ iio_attr -d
IIO context has 2 devices:
        iio:device0, xadc: found 1 device attributes
        iio_sysfs_trigger: found 2 device attributes
```
it shows only xadc and sysfs

then try iio_info -a but i found problem with avahi, then i install it through this command 
`sudo apt-get install avahi-daemon avahi-discover avahi-utils libnss-mdns mdns-scan`
and when try again i also can't see the ad9361
```

xilinx@pynq:~$ iio_info -s
Available contexts:
        0: (xadc on MicroPhase, ANTSDR-E200) [local:]

```

even when print dmesg there are no ad9361 
`dmesg | grep ad93`

**Comment by black-pigeon** [comment]
you need to relaod the bitstream and devicetree overlay. you can find a demo on the pynq notebook folder.

**Comment by Mojosekiz** [comment]
> you need to relaod the bitstream and devicetree overlay. you can find a demo on the pynq notebook folder.

Thank you for replay.
is there any already compiled basic file for bitstream and devicetree ? 

also for reload it i must open python and excute this command right? 
`ol = Overlay('your_overlay.bit', dtbo="your_overlay.dtb")`

**Comment by black-pigeon** [comment]
If you download the prebuilt image, you will find these files in the jupyter_notebooks folder, wo have a script to load the bit stream and dtbo, and using ad9361 to capture same data.

**Comment by Mojosekiz** [comment]
> jupyter_notebooks

Thank you it's working now when i'm using jupyter example :) :+1:
